### ISSUE TITLE
first issue

### ISSUE THREAD

**Issue by dirtyvagabond** [dirtyvagabond/jackalope-github-test#1]
this is the first issue!

**Comment by ava-v** [comment]
commenting on 1!

**Comment by ava-v** [comment]
I'm going to close this due to extreme age. If you'd like to keep it open: re-open, make sure there is an assignee, and explain why you are re-opening. If you're not sure who the assignee should be then please assign to 'dirtyvagabond'.

Yours,
Ava

p.s.: Happy Winter Holiday Times! :snowflake: :snowman: :gift: :snowman: :snowflake:

**Comment by ava-v** [comment]
I'm closing this as stale. If you'd like to keep it open, please:
1. add a comment to explain why you'd like to keep it open
2. specify an appropriate assignee
3. re-open the issue
